- name: debug
  debug:
    msg: "yo"
- name: install services
  yum:
    name: ["dnsmasq", "syslinux", "vsftpd"]
    state: present 

- name: copy dnsmasq.conf
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: copy vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd/vsftpd.conf

- name: prepare /var/lib/tftpboot dir
  file:
    path: /var/lib/tftpboot
    state: directory

- name: copy syslinux to /var/lib/tftpboot
  synchronize:
    src: /usr/share/syslinux/
    dest: /var/lib/tftpboot/ 

- name: prepare dir for default pxe
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory

- name: copy default to /var/lib/tftpboot/pxelinux.cfg
  copy:
    src: default
    dest: /var/lib/tftpboot/pxelinux.cfg/

- name: prepare dir for centos8 source
  file:
    path: /var/lib/tftpboot/centos8
    state: directory

- name: fetch vmlinuz & initrd.img for centos8
  get_url:
    url: http://mirror.centos.org/centos/8/BaseOS/x86_64/os/isolinux/vmlinuz
    dest: /var/lib/tftpboot/centos8/

- name: fetch initrd.img for centos8
  get_url:
    url: http://mirror.centos.org/centos/8/BaseOS/x86_64/os/isolinux/initrd.img
    dest: /var/lib/tftpboot/centos8/

- name: prepare dir for vsfptpd /var/ftp/pub
  file:
    path: /var/ftp/pub
    state: directory
    mode: '0755'

- name: prepare dir for centos8 /var/ftp/pub/centos8
  file:
    path: /var/ftp/pub/centos8
    state: directory
    mode: '0755'

- name: prepare kickstart files (after loop)
  copy:
    src: centos-ks_10.10.10.20.cfg
    dest: /var/ftp/pub/

- name: fetch cento8 from mirror.cntos.org
  shell:  lftp -c "open http://mirror.centos.org/centos/8/BaseOS/x86_64/os/ ; mirror -c -e . /var/ftp/pub/centos8"

- name: ugly dirty fix for non disabling selinux 
  shell: restorecon -R -v /var/lib/tftpboot

- name: enable fpt service firewall
  firewalld:
    service: ftp
    permanent: true
    state: enabled 

- name: enable dns service firewall
  firewalld:
    service: dns
    permanent: true
    state: enabled

- name: enable dhcp service firewall
  firewalld:
    service: dhcp
    permanent: true
    state: enabled

- name: enable 69/udp port firewall
  firewalld:
    port: 69/udp
    permanent: true
    state: enabled

- name: enable 4011/udp port firewall
  firewalld:
    port: 4011/udp
    permanent: true
    state: enabled

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart and enable service dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: restart and enable service vsfptd
  systemd:
    name: vsftpd
    state: restarted
    enabled: yes