- name: add deploy group
  group: 
    name: deploy
    state: present
    gid: 1050
  when: server | bool

- name: add docker group
  group:
    name: docker
    state: present
  when: server | bool

- name: add deployment user
  user: 
    name: deploy
    uid: 1050
    groups: deploy,docker
    append: yes
  when: server | bool