# - name: add deploy group
#   group: 
#     name: deploy
#     state: present
#     gid: 1050
#   when: server | bool

- name: add docker group
  group:
    name: docker
    state: present
  when: server | bool

- name: add deployment user
  user: 
    name: deploy
    shell: /bin/bash
    # uid: 1050
    groups: deploy,docker
    append: yes
  when: server | bool

- name: add pub_key for auto login via deployment user
  authorized_key:
    user: deploy
    state: present
    key: '{{ item }}'
  with_file:
    - deploy_pub
  when: server | bool

# - name: made deploy part of sudoers , passwordless (which is sec issue in real world)
#   lineinfile:
#     path: /etc/sudoers
#     line: "deploy        ALL=(ALL)       NOPASSWD: ALL"
#     validate: visudo -cf %s
