- name: add deploy group
  group: 
    name: deploy
    state: present
    gid: 1050
  when: server | bool

- name: add docker group
  group:
    name: docker
    state: present
  when: server | bool

- name: add deployment user
  user: 
    name: deploy
    shell: /bin/bash
    uid: 1050
    groups: deploy,docker
    append: yes
  when: server | bool

- name: add pub_key for auto login via deployment user
  ansible.posix.authorized_key:
    user: deploy
    state: present
    key: deploy_pub