---
- hosts: localhost
  become: yes
  tasks:

    - include_role:
        name: hello_world

    - include_role:
        name: template

    - include_role:
        name: common

    - include_role:
        name: users
      vars: 
        server: true
    
    - include_role:
        name: docker-centos
      when: ansible_distribution == "CentOS"
    
    - include_role:
        name: cleanup
        