---
- hosts: localhost

  tasks:

    - include_role:
        name: hello_world

    - include_role:
        name: template

    - include_role:
        name: common

    - include_role:
        name: users
        vars: 
          server: true