---
- hosts: localhost
  become: yes
  vars:
    deploy_docker: False
  tasks:

    - include_role:
        name: hello_world

    - include_role:
        name: template

    - include_role:
        name: common

    - include_role:
        name: users
      vars: 
        server: true
    
    - include_role:
        name: docker-centos
      when: ansible_distribution == "CentOS" and deploy_docker | bool
    
    - include_role:
        name: cleanup
        